version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_API_BASE_URL= http://fictional-yodel-x77wwxg7pjhv4rw-8000.app.github.dev
